controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    pid_controller:
      type: pid_controller/PidController

pid_controller:
  ros__parameters:
    dof_names:
      - joint_1
      - joint_2
      - joint_3
      - joint_4


    command_interface: velocity

    reference_and_state_interfaces: ["velocity","position"]

    gains:
      joint_1: {p: 0.025, i: 0.0150, d: 0.00215, i_clamp_max: 1.0, i_clamp_min: -1.0}
      joint_2: {p: 0.025, i: 0.0150, d: 0.00215, i_clamp_max: 1.0, i_clamp_min: -1.0}
      joint_3: {p: 0.025, i: 0.0150, d: 0.00215, i_clamp_max: 1.0, i_clamp_min: -1.0}
      joint_4: {p: 0.025, i: 0.0150, d: 0.00215, i_clamp_max: 1.0, i_clamp_min: -1.0}
