controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    pid_controller:
      type: pid_controller/PidController

pid_controller:
  ros__parameters:
    dof_names:
      - joint_1

    command_interface: velocity

    reference_and_state_interfaces: ["velocity","position"]

    gains:
      joint_1: {p: 1.0, i: 2.0, d: 10.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
